---
title: "Exercise 2: Bayesian Linear Regression"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bayesian linear regression model

We have the model


$$
\begin{aligned}
y_i \mid \boldsymbol \beta &\sim \mathcal{N}(\boldsymbol  x_i^{T} \boldsymbol \beta, \phi^{-1}), \quad i=1,\ldots,n; \\
\boldsymbol  \beta \mid \kappa &\sim \mathcal{N}(0,\kappa^{-1}\boldsymbol{\text{I}}); \\
    \kappa &\sim \text{Gamma}(a_0, b_0);
\end{aligned}
$$
where $\phi=1/\sigma^2$ is the precision parameter, which we assume is known, $\boldsymbol x_i, \ i=1,\ldots,n$ are known covariates, $\boldsymbol \beta \in \mathbb{R}^p$ includes the intercept, and is unknown, and $\boldsymbol{\text{I}}$ is the identity matrix. Assume $a_0$ and $b_0$ are known.

## Exercise 

We want a mean-field approximation to the posterior 

$$
p(\boldsymbol \beta, \kappa \mid \boldsymbol y)
$$

on the form

$$
q(\boldsymbol \beta, \kappa) = q(\boldsymbol \beta) q(\kappa).
$$

First, derive the CAVI updates. Then implement the algorithm, and run on simulated data with one covariate $x_{i,1} \sim \mathcal{N}(0,1)$, $n=50$, $\phi=0.5$, $\beta_0 = -1, \beta_1 = 2$, $a_0=b_0=0.001$. Assess convergence by the variational factors, or derive the ELBO to assess convergence. Visualize the resulting bivariate Gaussian approximation for the intercept $\beta_0$ and coefficient $\beta_1$.

## Solution

For $\kappa$, the variational approximation is on the form 

$$
q(\kappa) \propto \text{Gamma}(a_n,b_n);
$$

with 

$$
a_n= a_0+\frac{p}{2}, \quad b_n = b_0 + \frac{\mathbb{E}_{q_{\boldsymbol \beta}}[\boldsymbol\beta^{T}\boldsymbol \beta]}{2}.
$$
For $\boldsymbol\beta$, the variational approximation is on the form

$$
q(\boldsymbol\beta) \propto \mathcal{N}(\boldsymbol m_n, \boldsymbol S_n);
$$
with 

$$
\boldsymbol S_n = (\mathbb{E}_{q_\kappa}[\kappa]\boldsymbol{\text{I}} + \phi \boldsymbol X^{T} \boldsymbol X)^{-1}, \quad \boldsymbol m_n = \phi \boldsymbol S_n \boldsymbol X^{T}\boldsymbol y;
$$
where 


$$
\mathbb{E}_{q_\kappa}[\kappa] = \frac{a_n}{b_n}, \quad \mathbb{E}_{q_{\boldsymbol \beta}}[\boldsymbol\beta^{T}\boldsymbol \beta] = \boldsymbol m_n^{T} \boldsymbol m_n+ \text{tr}(\boldsymbol S_n).
$$

R code is given in a separate file.


